# Generated by Django 3.0.4 on 2020-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название товара')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на товар')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('discount_price', models.PositiveIntegerField(blank=True, verbose_name='Цена по скидке')),
                ('is_available', models.BooleanField(verbose_name='Товар в наличии')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
