# Generated by Django 3.0.4 on 2020-04-05 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200404_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Свойства товара'),
        ),
    ]
