# Generated by Django 3.0.4 on 2020-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200406_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, default='default_img/product.jpg', null=True, upload_to='Shop/Product/%Y/%m/%d/%H', verbose_name='Изображения для предпросмотра'),
        ),
    ]
