# Generated by Django 3.0.4 on 2020-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, default='default_img/product.jpg', null=True, upload_to='2e/', verbose_name='Изображения для предпросмотра'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='Shop/Product/Image', verbose_name='Изображения товара'),
        ),
    ]
