# Generated by Django 3.0.4 on 2021-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200813_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена по скидке'),
        ),
    ]
