# Generated by Django 3.2.5 on 2021-07-15 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0016_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('order_notes', models.CharField(max_length=512, verbose_name='Примечания к заказу')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен заказ')),
                ('is_coupon_applied', models.BooleanField(default=False, verbose_name='Применен купон')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Оформленный товар',
                'verbose_name_plural': 'Оформленные товары',
                'ordering': ['-date_create'],
            },
        ),
    ]
