# Generated by Django 3.2.5 on 2021-07-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Купон')),
                ('discount', models.PositiveIntegerField(max_length=100, verbose_name='Скидка %')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма активации')),
                ('quantity_activation', models.PositiveIntegerField(verbose_name='Количество активаций')),
                ('active_from', models.DateTimeField(verbose_name='Активен от')),
                ('active_to', models.DateTimeField(verbose_name='Активен до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_coupon_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon'),
        ),
    ]
