# Generated by Django 3.2.5 on 2021-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='Купон'),
        ),
    ]
