# Generated by Django 3.2.5 on 2021-07-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.CharField(blank=True, max_length=512, verbose_name='Примечания к заказу'),
        ),
    ]
