# Generated by Django 3.2.5 on 2021-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210812_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialcategoryproduct',
            options={'verbose_name': 'Специальная категория', 'verbose_name_plural': 'Специальные категории'},
        ),
        migrations.AddField(
            model_name='specialcategoryproduct',
            name='type_slider',
            field=models.CharField(choices=[('row1', 'Строка тип 1'), ('row2', 'Строка тип 2'), ('grid', 'Сетка')], default=123, max_length=16, verbose_name='Тип слайдера'),
            preserve_default=False,
        ),
    ]
